### ISSUE TITLE
corretto 20 based on AL2023

### ISSUE THREAD

**Issue by klubi** [corretto/corretto-docker#164]
Hi

Since AL2023 is already in GA would be nice to have `corretto:20` version based on 2023 aside of AL2.

Is there a chance for such image?

Thanks!

**Comment by lutkerd** [comment]
Thanks for bringing this up, we'll see when we can get that added and we will update this issue soon.

**Comment by rgithubli** [comment]
Hi @klubi , we finished creating Docker image for 20 on al2023. It's now available on Dockerhub and ECR public. You can pull the image via:

```
# from ECR public
docker pull public.ecr.aws/amazoncorretto/amazoncorretto:20-al2023-generic
```


or 

```
# from Dockerhub
docker pull amazoncorretto:20-al2023-generic
```


**Callout**: 20 doesn't have al2023 binary(see [corretto 20 download page](https://docs.aws.amazon.com/corretto/latest/corretto-20-ug/downloads-list.html)) so we built the docker image via installing generic linux corretto 20 on al2023. You might need to install using `dnf` or `yum` if any dependencies are missing.

I'm closing this issue since the image is available. Feel free to reopen if you have any issues.
