### ISSUE TITLE
Vulnerability ALAS2-2020-1466

### ISSUE THREAD

**Issue by mike-neck** [corretto/corretto-docker#22]
Image scan on ECR reported [ALAS2-2020-1466](https://alas.aws.amazon.com/AL2/ALAS-2020-1466.html) on my image built from amazoncorretto `11.0.8` and `8u265`.

It seems that there is `libxml2` `2.9.1` in the `amazoncorretto` images.

![image](https://user-images.githubusercontent.com/640317/89998704-d72f6980-dcc8-11ea-84dc-a9918f1c875b.png)

**Comment by alvdavi** [comment]
Hi,

Although the ALAS states that libxml2 versions through 2.9.8 are affected by different CVEs, it also states that all the problems listed have been fixed on libxml2.9.1-6. This means developers have decided to backport the security patches into 2.9.1, instead of updating the library to newer versions (which would include other non-security related changes).

If you look at the properties of the package:
```
docker run amazoncorretto:11.0.8 yum info -v libxml2.x86_64
...
Installed Packages
Name        : libxml2
Arch        : x86_64
Version     : 2.9.1
Release     : 6.amzn2.4.1
Size        : 1.6 M
Repo        : installed
Committer   : David King <dking@redhat.com>
Committime  : Fri Nov  1 12:00:00 2019
Buildtime   : Wed Jul 15 19:54:00 2020
Install time: Fri Jul 24 16:01:08 2020
Installed by: System <unset>
Changed by  : System <unset>
```

You can see how the package was recently rebuilt, matching the expected date for the ALAS. This seems to be a false positive in the tool, I will let the ECR Scanning team know.

**Comment by alvdavi** [comment]
Hi,

This has been fixed.
