### ISSUE TITLE
Need amazon corretto jdk based on alpine 3.13 

### ISSUE THREAD

**Issue by gyanu1** [corretto/corretto-docker#54]
**Alpine Linux 3.13** was released back in january 2021 with significant updates to kernel and other packages. There has already been 4 minor release (**3.13.4 latest**). It would be good to have corretto docker image based on alpine linux 3.13.

**Comment by jguo11** [comment]
@gyanu1 Thanks for reaching out. We will looking into this and let you know once it's ready.

**Comment by severusdenton** [comment]
I believe this is required in order to remediate CVE-2021-3177 (fix applied in Alpine Linux 3.13.3).

**Comment by cliveverghese** [comment]
Thanks for reaching out. We've verified that the Alpine images we currently ship are not susceptible to CVE-2021-3177 since they don't include Python installed by default. If you choose to install it, the updated version of Python (3.8.8) will be installed, which is not susceptible to CVE-2021-3177. Alpine 3.12 is supported until 2022-05-01 and upgrading to 3.13 is on our radar. We'll have more to share in the future.
